version: '3'
services:
  catalog:
    build: ./catalog_service
    ports:
      - "3001:3001"
    container_name: catalog_service

  order:
    build: ./order_service
    ports:
      - "3002:3002"
    depends_on:
      - catalog
    container_name: order_service

  client:
    build: ./client_service
    ports:
      - "3000:3000"
    depends_on:
      - catalog
      - order
    container_name: client_service
